name: Publish Docker image to Docker Hub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# https://docs.docker.com/build/ci/github-actions/multi-platform/
jobs:
  docker:
    name: build-and-publish
    runs-on: ubuntu-22.04
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Test changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
              src/**
              build/**
              mk/**
              tests/**
              tools/**
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'push'}}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name == 'push' }}
          tags: sysprog21/rv32emu:latest
